[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"]
remappings = ["@chainlink=lib/chainlink-brownie-contracts"]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
